repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "django"]
        files: ^(api|documents|doc_processor)/.*\.py$
        
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^(api|documents|doc_processor)/.*\.py$
        args: [--max-line-length=88, --extend-ignore=E501]