name: Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      DJANGO_SETTINGS_MODULE: doc_processor.settings
      DJANGO_SECRET_KEY: test-secret-key-for-ci
      DEBUG: True
      ALLOWED_HOSTS: "*"
      OCR_CACHE_DIR: /tmp/ocr-cache

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          tesseract-ocr \
          tesseract-ocr-eng \
          libgl1-mesa-dev \
          libglib2.0-0 \
          libsm6 \
          libxext6 \
          libxrender1 \
          libgomp1 \
          libgthread-2.0-0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements.dev.txt

    - name: Run Django migrations
      run: |
        python manage.py migrate --run-syncdb

    - name: Run fast tests
      run: |
        python run_tests_fast.py

    - name: Run full test suite with coverage
      run: |
        python -m pytest tests/ --cov=. --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
